  - name: Generate changelog
    uses: fabernovel/github-changelog-generator-action@v1
    with:
      # You can pass any parameters from https://github.com/github-changelog-generator/github-changelog-generator/wiki/Advanced-change-log-generation-examples#additional-options
      options: --token ${{ secrets.GITHUB_TOKEN }}